export const sampleClients = [
  {
    id: "client-001",
    firstName: "Jane",
    middleName: "A.",
    lastName: "Doe",
    email: "jane.doe@example.com",
    phoneNumber: "+2348012345678",
    address: {
      id: 1,
      addressLine: "123 Main St",
      landmark: "Near Central Park",
      town: "Ikeja",
      lga: "Ikeja",
      state: "Lagos",
      zipCode: "100001",
      country: "Nigeria",
    },
    imgUrl: "https://randomuser.me/api/portraits/women/1.jpg",
    isVerified: true,
    verificationDocument: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    reviews: "Jane is a great client.",
    experienceYears: 2,
    portfolio: "https://www.behance.net/gallery/94721953/Portfolio-Sample",
  },
  {
    id: "client-002",
    firstName: "John",
    middleName: "B.",
    lastName: "Smith",
    email: "john.smith@example.com",
    phoneNumber: "+2348012345679",
    address: {
      id: 2,
      addressLine: "456 Market Rd",
      landmark: "Opposite Mall",
      town: "Yaba",
      lga: "Yaba",
      state: "Lagos",
      zipCode: "100002",
      country: "Nigeria",
    },
    imgUrl: "https://randomuser.me/api/portraits/men/2.jpg",
    isVerified: false,
    verificationDocument: "",
    reviews: "John is a regular client.",
    experienceYears: 1,
    portfolio: "",
  },
  {
    id: "client-003",
    firstName: "Mary",
    middleName: "C.",
    lastName: "Johnson",
    email: "mary.johnson@example.com",
    phoneNumber: "+2348012345680",
    address: {
      id: 3,
      addressLine: "789 Broad Ave",
      landmark: "Near Stadium",
      town: "Surulere",
      lga: "Surulere",
      state: "Lagos",
      zipCode: "100003",
      country: "Nigeria",
    },
    imgUrl: "https://randomuser.me/api/portraits/women/3.jpg",
    isVerified: true,
    verificationDocument: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    reviews: "Mary is a new client.",
    experienceYears: 0,
    portfolio: "",
  },
];