export const sampleQuotes = [
  {
    id: 301,
    fixRequestId: 101,
    fixerId: "fixer-001",
    clientId: "client-001",
    description: "Quote for fixing leaking kitchen sink, including parts and labor.",
    amount: 18000,
    createdAt: "2024-07-21T09:00:00Z",
    items: [
      {
        id: 1,
        quoteId: 301,
        name: "Pipe replacement",
        quantity: 1,
        unitPrice: 8000,
        price: 8000,
      },
      {
        id: 2,
        quoteId: 301,
        name: "Labor",
        quantity: 2,
        unitPrice: 5000,
        price: 10000,
      },
    ],
    supportingImage: null,
    supportingDocument: null,
    supportingFiles: [],
  },
  {
    id: 302,
    fixRequestId: 101,
    fixerId: "fixer-002",
    clientId: "client-001",
    description: "Alternative quote for kitchen sink repair.",
    amount: 20000,
    createdAt: "2024-07-21T10:00:00Z",
    items: [
      {
        id: 3,
        quoteId: 302,
        name: "Pipe and sealant",
        quantity: 1,
        unitPrice: 12000,
        price: 12000,
      },
      {
        id: 4,
        quoteId: 302,
        name: "Labor",
        quantity: 2,
        unitPrice: 4000,
        price: 8000,
      },
    ],
    supportingImage: null,
    supportingDocument: null,
    supportingFiles: [],
  },
  {
    id: 303,
    fixRequestId: 102,
    fixerId: "fixer-002",
    clientId: "client-002",
    description: "Quote for electrical wiring check and repair.",
    amount: 30000,
    createdAt: "2024-07-23T11:00:00Z",
    items: [
      {
        id: 5,
        quoteId: 303,
        name: "Wiring materials",
        quantity: 1,
        unitPrice: 15000,
        price: 15000,
      },
      {
        id: 6,
        quoteId: 303,
        name: "Labor",
        quantity: 2,
        unitPrice: 7500,
        price: 15000,
      },
    ],
    supportingImage: null,
    supportingDocument: null,
    supportingFiles: [],
  },
  {
    id: 304,
    fixRequestId: 106,
    fixerId: "fixer-001",
    clientId: "client-003",
    description: "Quote for painting living room walls, including paint and labor.",
    amount: 18000,
    createdAt: "2024-07-31T12:00:00Z",
    items: [
      {
        id: 7,
        quoteId: 304,
        name: "Paint (light blue)",
        quantity: 5,
        unitPrice: 2000,
        price: 10000,
      },
      {
        id: 8,
        quoteId: 304,
        name: "Labor",
        quantity: 2,
        unitPrice: 4000,
        price: 8000,
      },
    ],
    supportingImage: null,
    supportingDocument: null,
    supportingFiles: [],
  },
  {
    id: 305,
    fixRequestId: 108,
    fixerId: "fixer-002",
    clientId: "client-002",
    description: "Quote for replacing broken window with shatterproof glass.",
    amount: 22000,
    createdAt: "2024-08-02T14:00:00Z",
    items: [
      {
        id: 9,
        quoteId: 305,
        name: "Shatterproof glass",
        quantity: 1,
        unitPrice: 15000,
        price: 15000,
      },
      {
        id: 10,
        quoteId: 305,
        name: "Labor",
        quantity: 1,
        unitPrice: 7000,
        price: 7000,
      },
    ],
    supportingImage: null,
    supportingDocument: null,
    supportingFiles: [],
  },
  {
    id: 306,
    fixRequestId: 110,
    fixerId: "fixer-002",
    clientId: "client-001",
    description: "Quote for installing ceiling fan in master bedroom.",
    amount: 9000,
    createdAt: "2024-08-04T10:00:00Z",
    items: [
      {
        id: 11,
        quoteId: 306,
        name: "Installation labor",
        quantity: 1,
        unitPrice: 9000,
        price: 9000,
      },
    ],
    supportingImage: null,
    supportingDocument: null,
    supportingFiles: [],
  },
];