export const sampleFixers = [
  {
    id: "fixer-001",
    firstName: "Emeka",
    middleName: "D.",
    lastName: "Okafor",
    email: "emeka.okafor@example.com",
    phoneNumber: "+2348012345681",
    address: {
      id: 4,
      addressLine: "12 Fixer Lane",
      landmark: "By Workshop",
      town: "Lekki",
      lga: "Eti-Osa",
      state: "Lagos",
      zipCode: "100004",
      country: "Nigeria",
    },
    imgUrl: "https://randomuser.me/api/portraits/men/4.jpg",
    specializationId: 1,
    specializationName: "Plumbing",
    certifications: "Certified Plumber",
    verificationDocument: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    isVerified: true,
    rating: 4.8,
    location: "Lekki, Lagos",
    isAvailable: true,
    reviews: "Excellent and reliable.",
    experienceYears: 5,
    portfolio: "https://www.behance.net/gallery/94721953/Portfolio-Sample",
    rateType: "hourly",
    rate: 5000,
  },
  {
    id: "fixer-002",
    firstName: "Aisha",
    middleName: "E.",
    lastName: "Bello",
    email: "aisha.bello@example.com",
    phoneNumber: "+2348012345682",
    address: {
      id: 5,
      addressLine: "34 Artisan St",
      landmark: "Near Mosque",
      town: "Victoria Island",
      lga: "Eti-Osa",
      state: "Lagos",
      zipCode: "100005",
      country: "Nigeria",
    },
    imgUrl: "https://randomuser.me/api/portraits/women/5.jpg",
    specializationId: 2,
    specializationName: "Electrical",
    certifications: "Certified Electrician",
    verificationDocument: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    isVerified: false,
    rating: 4.2,
    location: "Victoria Island, Lagos",
    isAvailable: false,
    reviews: "Professional and prompt.",
    experienceYears: 3,
    portfolio: "https://www.behance.net/gallery/94721953/Portfolio-Sample",
    rateType: "fixed",
    rate: 15000,
  },
];