export const sampleFixRequests = [
  {
    id: 101,
    title: "Demo 01 - Fix leaking kitchen sink",
    jobDescription: "The kitchen sink is leaking from the pipe underneath. Water drips onto the cabinet floor whenever the tap is used. Needs urgent repair to prevent further damage.",
    specializationId: 1,
    specialization: { id: 1, name: "Plumbing" },
    addressId: 1,
    address: { addressLine: "123 Main St", landmark: "Near Central Park", town: "Ikeja", lga: "Ikeja", state: "Lagos", zipCode: "100001", country: "Nigeria" },
    location: "Ikeja, Lagos",
    preferredSchedule: "2024-07-25T10:00:00Z",
    fixerStatuses: [
      { fixerId: "fixer-001", status: "Booked" },
      { fixerId: "fixer-002", status: "Accepted" }
    ],
    clientId: "client-001",
    status: "Booked",
    supportingImage: { id: 1, fileName: "sink.jpg", fileType: "image/jpeg", fileUrl: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80" },
    supportingDocument: { id: 2, fileName: "sink-invoice.pdf", fileType: "application/pdf", fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf" },
    supportingFiles: [
      { id: 3, fileName: "sink-specs.docx", fileType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", fileUrl: "https://file-examples.com/wp-content/uploads/2017/02/file-sample_100kB.docx" },
      { id: 4, fileName: "sink-photo2.jpg", fileType: "image/jpeg", fileUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80" },
    ],
    urgency: "High",
    budget: 20000,
    createdAt: "2024-07-20T08:00:00Z",
    updatedAt: "2024-07-24T12:00:00Z",
    quotes: [301, 302],
  },
  {
    id: 102,
    title: "Demo 02 - Electrical wiring check",
    jobDescription: "Frequent power outages in the living room. Suspect faulty wiring or loose connections. Need a professional to inspect and fix any issues.",
    specializationId: 2,
    specialization: { id: 2, name: "Electrical" },
    addressId: 2,
    address: { addressLine: "456 Market Rd", landmark: "Opposite Mall", town: "Yaba", lga: "Yaba", state: "Lagos", zipCode: "100002", country: "Nigeria" },
    location: "Yaba, Lagos",
    preferredSchedule: "2024-07-28T14:00:00Z",
    fixerStatuses: [
      { fixerId: "fixer-002", status: "Booked" },
      { fixerId: "fixer-001", status: "Rejected" }
    ],
    clientId: "client-002",
    status: "Completed",
    supportingImage: { id: 5, fileName: "wiring.jpg", fileType: "image/jpeg", fileUrl: "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80" },
    supportingDocument: { id: 6, fileName: "wiring-report.pdf", fileType: "application/pdf", fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf" },
    supportingFiles: [
      { id: 7, fileName: "wiring-specs.docx", fileType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", fileUrl: "https://file-examples.com/wp-content/uploads/2017/02/file-sample_100kB.docx" },
    ],
    urgency: "Medium",
    budget: 30000,
    createdAt: "2024-07-22T09:00:00Z",
    updatedAt: "2024-07-28T16:00:00Z",
    quotes: [303],
  },
  {
    id: 103,
    title: "Demo 03 - Install new water heater",
    jobDescription: "Need a new water heater installed in the bathroom. The old one has stopped working. Please recommend a reliable brand and handle installation.",
    specializationId: 1,
    specialization: { id: 1, name: "Plumbing" },
    addressId: 3,
    address: { addressLine: "789 Broad Ave", landmark: "Near Stadium", town: "Surulere", lga: "Surulere", state: "Lagos", zipCode: "100003", country: "Nigeria" },
    location: "Surulere, Lagos",
    preferredSchedule: "2024-07-30T09:00:00Z",
    fixerStatuses: [
      { fixerId: "fixer-001", status: "Pending" }
    ],
    clientId: "client-003",
    status: "Pending",
    supportingImage: null,
    supportingDocument: null,
    supportingFiles: [],
    urgency: "Medium",
    budget: 40000,
    createdAt: "2024-07-25T10:00:00Z",
    updatedAt: "2024-07-30T10:00:00Z",
    quotes: [],
  },
  {
    id: 104,
    title: "Demo 04 - Fix broken bathroom tap",
    jobDescription: "The bathroom tap is broken and water is leaking continuously. Needs urgent replacement or repair.",
    specializationId: 1,
    specialization: { id: 1, name: "Plumbing" },
    addressId: 1,
    address: { addressLine: "123 Main St", landmark: "Near Central Park", town: "Ikeja", lga: "Ikeja", state: "Lagos", zipCode: "100001", country: "Nigeria" },
    location: "Ikeja, Lagos",
    preferredSchedule: "2024-08-01T09:00:00Z",
    fixerStatuses: [
      { fixerId: "fixer-001", status: "Booked" }
    ],
    clientId: "client-001",
    status: "Booked",
    supportingImage: { id: 12, fileName: "tap.jpg", fileType: "image/jpeg", fileUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80" },
    supportingDocument: null,
    supportingFiles: [],
    urgency: "Low",
    budget: 8000,
    createdAt: "2024-07-29T08:00:00Z",
    updatedAt: "2024-07-31T12:00:00Z",
    quotes: [],
  },
  {
    id: 105,
    title: "Demo 05 - Repair faulty air conditioner",
    jobDescription: "The air conditioner is not cooling properly and makes a loud noise. Needs diagnosis and repair before the weekend.",
    specializationId: 3,
    specialization: { id: 3, name: "HVAC" },
    addressId: 2,
    address: { addressLine: "456 Market Rd", landmark: "Opposite Mall", town: "Yaba", lga: "Yaba", state: "Lagos", zipCode: "100002", country: "Nigeria" },
    location: "Yaba, Lagos",
    preferredSchedule: "2024-08-02T15:00:00Z",
    fixerStatuses: [
      { fixerId: "fixer-002", status: "Booked" }
    ],
    clientId: "client-002",
    status: "Booked",
    supportingImage: null,
    supportingDocument: null,
    supportingFiles: [],
    urgency: "High",
    budget: 35000,
    createdAt: "2024-07-30T09:00:00Z",
    updatedAt: "2024-08-01T10:00:00Z",
    quotes: [],
  },
  {
    id: 106,
    title: "Demo 06 - Paint living room walls",
    jobDescription: "Looking to repaint the living room walls. Prefer light colors. Please provide paint options and estimated cost.",
    specializationId: 4,
    specialization: { id: 4, name: "Painting" },
    addressId: 3,
    address: { addressLine: "789 Broad Ave", landmark: "Near Stadium", town: "Surulere", lga: "Surulere", state: "Lagos", zipCode: "100003", country: "Nigeria" },
    location: "Surulere, Lagos",
    preferredSchedule: "2024-08-03T11:00:00Z",
    fixerStatuses: [
      { fixerId: "fixer-001", status: "Booked" }
    ],
    clientId: "client-003",
    status: "Booked",
    supportingImage: null,
    supportingDocument: null,
    supportingFiles: [],
    urgency: "Medium",
    budget: 18000,
    createdAt: "2024-07-31T11:00:00Z",
    updatedAt: "2024-08-02T12:00:00Z",
    quotes: [304],
  },
  {
    id: 107,
    title: "Demo 07 - Fix leaking roof",
    jobDescription: "There is a leak in the roof above the master bedroom. Water stains are visible on the ceiling. Needs urgent attention before the rainy season.",
    specializationId: 5,
    specialization: { id: 5, name: "Roofing" },
    addressId: 1,
    address: { addressLine: "123 Main St", landmark: "Near Central Park", town: "Ikeja", lga: "Ikeja", state: "Lagos", zipCode: "100001", country: "Nigeria" },
    location: "Ikeja, Lagos",
    preferredSchedule: "2024-08-04T08:00:00Z",
    fixerStatuses: [
      { fixerId: "fixer-002", status: "Pending" }
    ],
    clientId: "client-001",
    status: "Rejected",
    supportingImage: null,
    supportingDocument: null,
    supportingFiles: [],
    urgency: "High",
    budget: 50000,
    createdAt: "2024-08-01T08:00:00Z",
    updatedAt: "2024-08-03T09:00:00Z",
    quotes: [],
  },
  {
    id: 108,
    title: "Demo 08 - Replace broken window",
    jobDescription: "The living room window glass is shattered. Need a replacement pane and installation as soon as possible.",
    specializationId: 6,
    specialization: { id: 6, name: "Carpentry" },
    addressId: 2,
    address: { addressLine: "456 Market Rd", landmark: "Opposite Mall", town: "Yaba", lga: "Yaba", state: "Lagos", zipCode: "100002", country: "Nigeria" },
    location: "Yaba, Lagos",
    preferredSchedule: "2024-08-05T13:00:00Z",
    fixerStatuses: [
      { fixerId: "fixer-002", status: "Booked" }
    ],
    clientId: "client-002",
    status: "Booked",
    supportingImage: null,
    supportingDocument: null,
    supportingFiles: [],
    urgency: "Medium",
    budget: 22000,
    createdAt: "2024-08-02T10:00:00Z",
    updatedAt: "2024-08-04T11:00:00Z",
    quotes: [305],
  },
  {
    id: 109,
    title: "Demo 09 - Unclog bathroom drain",
    jobDescription: "Bathroom drain is clogged and water is backing up. Tried using a plunger but did not work. Need professional help.",
    specializationId: 1,
    specialization: { id: 1, name: "Plumbing" },
    addressId: 3,
    address: { addressLine: "789 Broad Ave", landmark: "Near Stadium", town: "Surulere", lga: "Surulere", state: "Lagos", zipCode: "100003", country: "Nigeria" },
    location: "Surulere, Lagos",
    preferredSchedule: "2024-08-06T10:00:00Z",
    fixerStatuses: [
      { fixerId: "fixer-001", status: "Booked" }
    ],
    clientId: "client-003",
    status: "Completed",
    supportingImage: null,
    supportingDocument: null,
    supportingFiles: [],
    urgency: "High",
    budget: 12000,
    createdAt: "2024-08-03T09:00:00Z",
    updatedAt: "2024-08-05T10:00:00Z",
    quotes: [],
  },
  {
    id: 110,
    title: "Demo 10 - Install ceiling fan",
    jobDescription: "Need to install a new ceiling fan in the guest room. The old fan has been removed. Wiring is available.",
    specializationId: 2,
    specialization: { id: 2, name: "Electrical" },
    addressId: 1,
    address: { addressLine: "123 Main St", landmark: "Near Central Park", town: "Ikeja", lga: "Ikeja", state: "Lagos", zipCode: "100001", country: "Nigeria" },
    location: "Ikeja, Lagos",
    preferredSchedule: "2024-08-07T12:00:00Z",
    fixerStatuses: [
      { fixerId: "fixer-002", status: "Booked" }
    ],
    clientId: "client-001",
    status: "Booked",
    supportingImage: null,
    supportingDocument: null,
    supportingFiles: [],
    urgency: "Low",
    budget: 9000,
    createdAt: "2024-08-04T11:00:00Z",
    updatedAt: "2024-08-06T12:00:00Z",
    quotes: [306],
  },
  {
    id: 111,
    title: "Demo 11 - Repair kitchen cabinet",
    jobDescription: "The kitchen cabinet door is loose and the hinges are broken. Needs repair or replacement of hinges.",
    specializationId: 6,
    specialization: { id: 6, name: "Carpentry" },
    addressId: 2,
    address: { addressLine: "456 Market Rd", landmark: "Opposite Mall", town: "Yaba", lga: "Yaba", state: "Lagos", zipCode: "100002", country: "Nigeria" },
    location: "Yaba, Lagos",
    preferredSchedule: "2024-08-08T14:00:00Z",
    fixerStatuses: [
      { fixerId: "fixer-001", status: "Pending" }
    ],
    clientId: "client-002",
    status: "Pending",
    supportingImage: null,
    supportingDocument: null,
    supportingFiles: [],
    urgency: "Medium",
    budget: 7000,
    createdAt: "2024-08-05T12:00:00Z",
    updatedAt: "2024-08-07T13:00:00Z",
    quotes: [],
  },
  {
    id: 112,
    title: "Demo 12 - Service generator",
    jobDescription: "The generator is due for routine servicing. Please check oil, filters, and overall condition. No major issues reported.",
    specializationId: 7,
    specialization: { id: 7, name: "Generator Repair" },
    addressId: 3,
    address: { addressLine: "789 Broad Ave", landmark: "Near Stadium", town: "Surulere", lga: "Surulere", state: "Lagos", zipCode: "100003", country: "Nigeria" },
    location: "Surulere, Lagos",
    preferredSchedule: "2024-08-09T09:00:00Z",
    fixerStatuses: [
      { fixerId: "fixer-001", status: "Booked" }
    ],
    clientId: "client-003",
    status: "Booked",
    supportingImage: null,
    supportingDocument: null,
    supportingFiles: [],
    urgency: "Low",
    budget: 15000,
    createdAt: "2024-08-06T10:00:00Z",
    updatedAt: "2024-08-08T11:00:00Z",
    quotes: [],
  },
];