// Sample data for dashboard design, population, and testing

export const sample = {
  clients: [
    {
      id: "client-001",
      firstName: "Jane",
      middleName: "A.",
      lastName: "Doe",
      email: "jane.doe@example.com",
      phoneNumber: "+2348012345678",
      address: {
        id: 1,
        addressLine: "123 Main St",
        landmark: "Near Central Park",
        town: "Ikeja",
        lga: "Ikeja",
        state: "Lagos",
        zipCode: "100001",
        country: "Nigeria",
      },
      imgUrl: "https://randomuser.me/api/portraits/women/1.jpg",
      isVerified: true,
      verificationDocument: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      reviews: "Jane is a great client.",
      experienceYears: 2,
      portfolio: "https://www.behance.net/gallery/94721953/Portfolio-Sample",
    },
    {
      id: "client-002",
      firstName: "John",
      middleName: "B.",
      lastName: "Smith",
      email: "john.smith@example.com",
      phoneNumber: "+2348012345679",
      address: {
        id: 2,
        addressLine: "456 Market Rd",
        landmark: "Opposite Mall",
        town: "Yaba",
        lga: "Yaba",
        state: "Lagos",
        zipCode: "100002",
        country: "Nigeria",
      },
      imgUrl: "https://randomuser.me/api/portraits/men/2.jpg",
      isVerified: false,
      verificationDocument: "",
      reviews: "John is a regular client.",
      experienceYears: 1,
      portfolio: "",
    },
    {
      id: "client-003",
      firstName: "Mary",
      middleName: "C.",
      lastName: "Johnson",
      email: "mary.johnson@example.com",
      phoneNumber: "+2348012345680",
      address: {
        id: 3,
        addressLine: "789 Broad Ave",
        landmark: "Near Stadium",
        town: "Surulere",
        lga: "Surulere",
        state: "Lagos",
        zipCode: "100003",
        country: "Nigeria",
      },
      imgUrl: "https://randomuser.me/api/portraits/women/3.jpg",
      isVerified: true,
      verificationDocument: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      reviews: "Mary is a new client.",
      experienceYears: 0,
      portfolio: "",
    },
  ],
  fixers: [
    {
      id: "fixer-001",
      firstName: "Emeka",
      middleName: "D.",
      lastName: "Okafor",
      email: "emeka.okafor@example.com",
      phoneNumber: "+2348012345681",
      address: {
        id: 4,
        addressLine: "12 Fixer Lane",
        landmark: "By Workshop",
        town: "Lekki",
        lga: "Eti-Osa",
        state: "Lagos",
        zipCode: "100004",
        country: "Nigeria",
      },
      imgUrl: "https://randomuser.me/api/portraits/men/4.jpg",
      specializationId: 1,
      specializationName: "Plumbing",
      certifications: "Certified Plumber",
      verificationDocument: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      isVerified: true,
      rating: 4.8,
      location: "Lekki, Lagos",
      isAvailable: true,
      reviews: "Excellent and reliable.",
      experienceYears: 5,
      portfolio: "https://www.behance.net/gallery/94721953/Portfolio-Sample",
      rateType: "hourly",
      rate: 5000,
    },
    {
      id: "fixer-002",
      firstName: "Aisha",
      middleName: "E.",
      lastName: "Bello",
      email: "aisha.bello@example.com",
      phoneNumber: "+2348012345682",
      address: {
        id: 5,
        addressLine: "34 Artisan St",
        landmark: "Near Mosque",
        town: "Victoria Island",
        lga: "Eti-Osa",
        state: "Lagos",
        zipCode: "100005",
        country: "Nigeria",
      },
      imgUrl: "https://randomuser.me/api/portraits/women/5.jpg",
      specializationId: 2,
      specializationName: "Electrical",
      certifications: "Certified Electrician",
      verificationDocument: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      isVerified: false,
      rating: 4.2,
      location: "Victoria Island, Lagos",
      isAvailable: false,
      reviews: "Professional and prompt.",
      experienceYears: 3,
      portfolio: "https://www.behance.net/gallery/94721953/Portfolio-Sample",
      rateType: "fixed",
      rate: 15000,
    },
  ],
   fixRequests: [
    {
      id: 101,
      title: "Demo 01 -Fix leaking kitchen sink",
      jobDescription: `The kitchen sink has developed a persistent leak that is causing water to pool under the cabinet. The leak appears to be coming from the pipe connection beneath the sink. Please inspect the plumbing, replace any faulty parts, and ensure the area is dry and secure after repair.`,
      specializationId: 1,
      specialization: { id: 1, name: "Plumbing" },
      addressId: 1,
      address: {
        addressLine: "123 Main St",
        landmark: "Near Central Park",
        town: "Ikeja",
        lga: "Ikeja",
        state: "Lagos",
        zipCode: "100001",
        country: "Nigeria",
      },
      location: "Ikeja, Lagos",
      preferredSchedule: "2024-07-25T10:00:00Z",
      fixerStatuses: [
        { fixerId: "fixer-001", status: "Accepted" },
        { fixerId: "fixer-002", status: "Accepted" }
      ],
      clientId: "client-001",
      status: "Booked", // Example: derived status
      supportingImage: {
        id: 1,
        fileName: "sink.jpg",
        fileType: "image/jpeg",
        fileUrl: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80",
      },
      supportingDocument: {
        id: 2,
        fileName: "sink-invoice.pdf",
        fileType: "application/pdf",
        fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      },
      supportingFiles: [
        {
          id: 3,
          fileName: "sink-specs.docx",
          fileType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          fileUrl: "https://file-examples.com/wp-content/uploads/2017/02/file-sample_100kB.docx",
        },
        {
          id: 4,
          fileName: "sink-photo2.jpg",
          fileType: "image/jpeg",
          fileUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
        },
      ],
    },
    {
      id: 102,
      title: "Demo 02 -Electrical wiring check",
      jobDescription: `There have been occasional sparks and flickering lights in the living room and kitchen. The wiring may be old or damaged. Please conduct a thorough inspection, repair any faulty wires, and ensure all electrical points are safe and compliant.`,
      specializationId: 2,
      specialization: { id: 2, name: "Electrical" },
      addressId: 2,
      address: {
        addressLine: "456 Market Rd",
        landmark: "Opposite Mall",
        town: "Yaba",
        lga: "Yaba",
        state: "Lagos",
        zipCode: "100002",
        country: "Nigeria",
      },
      location: "Yaba, Lagos",
      preferredSchedule: "2024-07-28T14:00:00Z",
      fixerStatuses: [
        { fixerId: "fixer-002", status: "Acceted" },
        { fixerId: "fixer-001", status: "Rejected" }
      ],
      clientId: "client-002",
      status: "Completed",
      supportingImage: {
        id: 5,
        fileName: "wiring.jpg",
        fileType: "image/jpeg",
        fileUrl: "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80",
      },
      supportingDocument: {
        id: 6,
        fileName: "wiring-report.pdf",
        fileType: "application/pdf",
        fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      },
      supportingFiles: [
        {
          id: 7,
          fileName: "wiring-specs.docx",
          fileType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          fileUrl: "https://file-examples.com/wp-content/uploads/2017/02/file-sample_100kB.docx",
        },
      ],
    },
    {
      id: 103,
      title: "Demo 03 -Install new water heater",
      jobDescription: `A new water heater needs to be installed in the bathroom. The old unit has been removed, and the new heater is ready for setup. Please handle all plumbing and electrical connections, test the heater for proper operation, and provide a brief usage guide.`,
      specializationId: 1,
      specialization: { id: 1, name: "Plumbing" },
      addressId: 3,
      address: {
        addressLine: "789 Broad Ave",
        landmark: "Near Stadium",
        town: "Surulere",
        lga: "Surulere",
        state: "Lagos",
        zipCode: "100003",
        country: "Nigeria",
      },
      location: "Surulere, Lagos",
      preferredSchedule: "2024-07-30T09:00:00Z",
      fixerStatuses: [
        { fixerId: "fixer-001", status: "Pending" },
        { fixerId: "fixer-002", status: "Rejected" }
      ],
      clientId: "client-003",
      status: "Pending",
      supportingImage: {
        id: 8,
        fileName: "heater.jpg",
        fileType: "image/jpeg",
        fileUrl: "https://images.unsplash.com/photo-1517816743773-6e0fd518b4a6?auto=format&fit=crop&w=400&q=80",
      },
      supportingDocument: {
        id: 9,
        fileName: "heater-manual.pdf",
        fileType: "application/pdf",
        fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      },
      supportingFiles: [
        {
          id: 10,
          fileName: "heater-specs.docx",
          fileType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          fileUrl: "https://file-examples.com/wp-content/uploads/2017/02/file-sample_100kB.docx",
        },
        {
          id: 11,
          fileName: "heater-photo2.jpg",
          fileType: "image/jpeg",
          fileUrl: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80",
        },
      ],
    },
    {
      id: 104,
      title: "Demo 04 -Fix leaking kitchen sink",
      jobDescription: `The kitchen sink has developed a persistent leak that is causing water to pool under the cabinet. The leak appears to be coming from the pipe connection beneath the sink. Please inspect the plumbing, replace any faulty parts, and ensure the area is dry and secure after repair.`,
      specializationId: 1,
      specialization: { id: 1, name: "Plumbing" },
      addressId: 1,
      address: {
        addressLine: "123 Main St",
        landmark: "Near Central Park",
        town: "Ikeja",
        lga: "Ikeja",
        state: "Lagos",
        zipCode: "100001",
        country: "Nigeria",
      },
      location: "Ikeja, Lagos",
      preferredSchedule: "2024-07-25T10:00:00Z",
      fixerStatuses: [
        { fixerId: "fixer-001", status: "Accepted" },
        { fixerId: "fixer-002", status: "Accepted" }
      ],
      clientId: "client-001",
      status: "Booked", // Example: derived status
      supportingImage: {
        id: 1,
        fileName: "sink.jpg",
        fileType: "image/jpeg",
        fileUrl: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80",
      },
      supportingDocument: {
        id: 2,
        fileName: "sink-invoice.pdf",
        fileType: "application/pdf",
        fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      },
      supportingFiles: [
        {
          id: 3,
          fileName: "sink-specs.docx",
          fileType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          fileUrl: "https://file-examples.com/wp-content/uploads/2017/02/file-sample_100kB.docx",
        },
        {
          id: 4,
          fileName: "sink-photo2.jpg",
          fileType: "image/jpeg",
          fileUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
        },
      ],
    },
    {
      id: 105,
      title: "Demo 05 -Electrical wiring check",
      jobDescription: `There have been occasional sparks and flickering lights in the living room and kitchen. The wiring may be old or damaged. Please conduct a thorough inspection, repair any faulty wires, and ensure all electrical points are safe and compliant.`,
      specializationId: 2,
      specialization: { id: 2, name: "Electrical" },
      addressId: 2,
      address: {
        addressLine: "456 Market Rd",
        landmark: "Opposite Mall",
        town: "Yaba",
        lga: "Yaba",
        state: "Lagos",
        zipCode: "100002",
        country: "Nigeria",
      },
      location: "Yaba, Lagos",
      preferredSchedule: "2024-07-28T14:00:00Z",
      fixerStatuses: [
        { fixerId: "fixer-002", status: "Acceted" },
        { fixerId: "fixer-001", status: "Rejected" }
      ],
      clientId: "client-002",
      status: "Completed",
      supportingImage: {
        id: 5,
        fileName: "wiring.jpg",
        fileType: "image/jpeg",
        fileUrl: "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80",
      },
      supportingDocument: {
        id: 6,
        fileName: "wiring-report.pdf",
        fileType: "application/pdf",
        fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      },
      supportingFiles: [
        {
          id: 7,
          fileName: "wiring-specs.docx",
          fileType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          fileUrl: "https://file-examples.com/wp-content/uploads/2017/02/file-sample_100kB.docx",
        },
      ],
    },
    {
      id: 106,
      title: "Demo 06 - Install new water heater",
      jobDescription: `A new water heater needs to be installed in the bathroom. The old unit has been removed, and the new heater is ready for setup. Please handle all plumbing and electrical connections, test the heater for proper operation, and provide a brief usage guide.`,
      specializationId: 1,
      specialization: { id: 1, name: "Plumbing" },
      addressId: 3,
      address: {
        addressLine: "789 Broad Ave",
        landmark: "Near Stadium",
        town: "Surulere",
        lga: "Surulere",
        state: "Lagos",
        zipCode: "100003",
        country: "Nigeria",
      },
      location: "Surulere, Lagos",
      preferredSchedule: "2024-07-30T09:00:00Z",
      fixerStatuses: [
        { fixerId: "fixer-001", status: "Pending" },
        { fixerId: "fixer-002", status: "Rejected" }
      ],
      clientId: "client-003",
      status: "Pending",
      supportingImage: {
        id: 8,
        fileName: "heater.jpg",
        fileType: "image/jpeg",
        fileUrl: "https://images.unsplash.com/photo-1517816743773-6e0fd518b4a6?auto=format&fit=crop&w=400&q=80",
      },
      supportingDocument: {
        id: 9,
        fileName: "heater-manual.pdf",
        fileType: "application/pdf",
        fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      },
      supportingFiles: [
        {
          id: 10,
          fileName: "heater-specs.docx",
          fileType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          fileUrl: "https://file-examples.com/wp-content/uploads/2017/02/file-sample_100kB.docx",
        },
        {
          id: 11,
          fileName: "heater-photo2.jpg",
          fileType: "image/jpeg",
          fileUrl: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80",
        },
      ],
    },
    {
      id: 107,
      title: "Demo 07 - Fix leaking kitchen sink",
      jobDescription: `The kitchen sink has developed a persistent leak that is causing water to pool under the cabinet. The leak appears to be coming from the pipe connection beneath the sink. Please inspect the plumbing, replace any faulty parts, and ensure the area is dry and secure after repair.`,
      specializationId: 1,
      specialization: { id: 1, name: "Plumbing" },
      addressId: 1,
      address: {
        addressLine: "123 Main St",
        landmark: "Near Central Park",
        town: "Ikeja",
        lga: "Ikeja",
        state: "Lagos",
        zipCode: "100001",
        country: "Nigeria",
      },
      location: "Ikeja, Lagos",
      preferredSchedule: "2024-07-25T10:00:00Z",
      fixerStatuses: [
        { fixerId: "fixer-001", status: "Accepted" },
        { fixerId: "fixer-002", status: "Accepted" }
      ],
      clientId: "client-001",
      status: "Booked", // Example: derived status
      supportingImage: {
        id: 1,
        fileName: "sink.jpg",
        fileType: "image/jpeg",
        fileUrl: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80",
      },
      supportingDocument: {
        id: 2,
        fileName: "sink-invoice.pdf",
        fileType: "application/pdf",
        fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      },
      supportingFiles: [
        {
          id: 3,
          fileName: "sink-specs.docx",
          fileType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          fileUrl: "https://file-examples.com/wp-content/uploads/2017/02/file-sample_100kB.docx",
        },
        {
          id: 4,
          fileName: "sink-photo2.jpg",
          fileType: "image/jpeg",
          fileUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
        },
      ],
    },
    {
      id: 108,
      title: "Demo 08 - Electrical wiring check",
      jobDescription: `There have been occasional sparks and flickering lights in the living room and kitchen. The wiring may be old or damaged. Please conduct a thorough inspection, repair any faulty wires, and ensure all electrical points are safe and compliant.`,
      specializationId: 2,
      specialization: { id: 2, name: "Electrical" },
      addressId: 2,
      address: {
        addressLine: "456 Market Rd",
        landmark: "Opposite Mall",
        town: "Yaba",
        lga: "Yaba",
        state: "Lagos",
        zipCode: "100002",
        country: "Nigeria",
      },
      location: "Yaba, Lagos",
      preferredSchedule: "2024-07-28T14:00:00Z",
      fixerStatuses: [
        { fixerId: "fixer-002", status: "Acceted" },
        { fixerId: "fixer-001", status: "Rejected" }
      ],
      clientId: "client-002",
      status: "Completed",
      supportingImage: {
        id: 5,
        fileName: "wiring.jpg",
        fileType: "image/jpeg",
        fileUrl: "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80",
      },
      supportingDocument: {
        id: 6,
        fileName: "wiring-report.pdf",
        fileType: "application/pdf",
        fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      },
      supportingFiles: [
        {
          id: 7,
          fileName: "wiring-specs.docx",
          fileType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          fileUrl: "https://file-examples.com/wp-content/uploads/2017/02/file-sample_100kB.docx",
        },
      ],
    },
    {
      id: 10,
      title: "Demo 09 -Install new water heater",
      jobDescription: `A new water heater needs to be installed in the bathroom. The old unit has been removed, and the new heater is ready for setup. Please handle all plumbing and electrical connections, test the heater for proper operation, and provide a brief usage guide.`,
      specializationId: 1,
      specialization: { id: 1, name: "Plumbing" },
      addressId: 3,
      address: {
        addressLine: "789 Broad Ave",
        landmark: "Near Stadium",
        town: "Surulere",
        lga: "Surulere",
        state: "Lagos",
        zipCode: "100003",
        country: "Nigeria",
      },
      location: "Surulere, Lagos",
      preferredSchedule: "2024-07-30T09:00:00Z",
      fixerStatuses: [
        { fixerId: "fixer-001", status: "Pending" },
        { fixerId: "fixer-002", status: "Rejected" }
      ],
      clientId: "client-003",
      status: "Pending",
      supportingImage: {
        id: 8,
        fileName: "heater.jpg",
        fileType: "image/jpeg",
        fileUrl: "https://images.unsplash.com/photo-1517816743773-6e0fd518b4a6?auto=format&fit=crop&w=400&q=80",
      },
      supportingDocument: {
        id: 9,
        fileName: "heater-manual.pdf",
        fileType: "application/pdf",
        fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      },
      supportingFiles: [
        {
          id: 10,
          fileName: "heater-specs.docx",
          fileType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          fileUrl: "https://file-examples.com/wp-content/uploads/2017/02/file-sample_100kB.docx",
        },
        {
          id: 11,
          fileName: "heater-photo2.jpg",
          fileType: "image/jpeg",
          fileUrl: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80",
        },
      ],
    },
    {
      id: 110,
      title: "Demo 10 -Fix leaking kitchen sink",
      jobDescription: `The kitchen sink has developed a persistent leak that is causing water to pool under the cabinet. The leak appears to be coming from the pipe connection beneath the sink. Please inspect the plumbing, replace any faulty parts, and ensure the area is dry and secure after repair.`,
      specializationId: 1,
      specialization: { id: 1, name: "Plumbing" },
      addressId: 1,
      address: {
        addressLine: "123 Main St",
        landmark: "Near Central Park",
        town: "Ikeja",
        lga: "Ikeja",
        state: "Lagos",
        zipCode: "100001",
        country: "Nigeria",
      },
      location: "Ikeja, Lagos",
      preferredSchedule: "2024-07-25T10:00:00Z",
      fixerStatuses: [
        { fixerId: "fixer-001", status: "Accepted" },
        { fixerId: "fixer-002", status: "Accepted" }
      ],
      clientId: "client-001",
      status: "Booked", // Example: derived status
      supportingImage: {
        id: 1,
        fileName: "sink.jpg",
        fileType: "image/jpeg",
        fileUrl: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80",
      },
      supportingDocument: {
        id: 2,
        fileName: "sink-invoice.pdf",
        fileType: "application/pdf",
        fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      },
      supportingFiles: [
        {
          id: 3,
          fileName: "sink-specs.docx",
          fileType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          fileUrl: "https://file-examples.com/wp-content/uploads/2017/02/file-sample_100kB.docx",
        },
        {
          id: 4,
          fileName: "sink-photo2.jpg",
          fileType: "image/jpeg",
          fileUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
        },
      ],
    },
    {
      id: 111,
      title: "Demo 11 - Electrical wiring check",
      jobDescription: `There have been occasional sparks and flickering lights in the living room and kitchen. The wiring may be old or damaged. Please conduct a thorough inspection, repair any faulty wires, and ensure all electrical points are safe and compliant.`,
      specializationId: 2,
      specialization: { id: 2, name: "Electrical" },
      addressId: 2,
      address: {
        addressLine: "456 Market Rd",
        landmark: "Opposite Mall",
        town: "Yaba",
        lga: "Yaba",
        state: "Lagos",
        zipCode: "100002",
        country: "Nigeria",
      },
      location: "Yaba, Lagos",
      preferredSchedule: "2024-07-28T14:00:00Z",
      fixerStatuses: [
        { fixerId: "fixer-002", status: "Acceted" },
        { fixerId: "fixer-001", status: "Rejected" }
      ],
      clientId: "client-002",
      status: "Completed",
      supportingImage: {
        id: 5,
        fileName: "wiring.jpg",
        fileType: "image/jpeg",
        fileUrl: "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80",
      },
      supportingDocument: {
        id: 6,
        fileName: "wiring-report.pdf",
        fileType: "application/pdf",
        fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      },
      supportingFiles: [
        {
          id: 7,
          fileName: "wiring-specs.docx",
          fileType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          fileUrl: "https://file-examples.com/wp-content/uploads/2017/02/file-sample_100kB.docx",
        },
      ],
    },
    {
      id: 112,
      title: "Demo 12 -Install new water heater",
      jobDescription: `A new water heater needs to be installed in the bathroom. The old unit has been removed, and the new heater is ready for setup. Please handle all plumbing and electrical connections, test the heater for proper operation, and provide a brief usage guide.`,
      specializationId: 1,
      specialization: { id: 1, name: "Plumbing" },
      addressId: 3,
      address: {
        addressLine: "789 Broad Ave",
        landmark: "Near Stadium",
        town: "Surulere",
        lga: "Surulere",
        state: "Lagos",
        zipCode: "100003",
        country: "Nigeria",
      },
      location: "Surulere, Lagos",
      preferredSchedule: "2024-07-30T09:00:00Z",
      fixerStatuses: [
        { fixerId: "fixer-001", status: "Pending" },
        { fixerId: "fixer-002", status: "Rejected" }
      ],
      clientId: "client-003",
      status: "Pending",
      supportingImage: {
        id: 8,
        fileName: "heater.jpg",
        fileType: "image/jpeg",
        fileUrl: "https://images.unsplash.com/photo-1517816743773-6e0fd518b4a6?auto=format&fit=crop&w=400&q=80",
      },
      supportingDocument: {
        id: 9,
        fileName: "heater-manual.pdf",
        fileType: "application/pdf",
        fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      },
      supportingFiles: [
        {
          id: 10,
          fileName: "heater-specs.docx",
          fileType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          fileUrl: "https://file-examples.com/wp-content/uploads/2017/02/file-sample_100kB.docx",
        },
        {
          id: 11,
          fileName: "heater-photo2.jpg",
          fileType: "image/jpeg",
          fileUrl: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80",
        },
      ],
    },
  ],

  bookings: [
    {
      id: 201,
      clientId: "client-001",
      fixerId: "fixer-001",
      quoteId: 301,
      bookingDate: "2024-07-25T10:00:00Z",
      status: "In Progress",
    },
    {
      id: 202,
      clientId: "client-002",
      fixerId: "fixer-002",
      quoteId: 302,
      bookingDate: "2024-07-20T09:00:00Z",
      status: "Completed",
    },
    {
      id: 203,
      clientId: "client-003",
      fixerId: "fixer-001",
      quoteId: 303,
      bookingDate: "2024-07-30T09:00:00Z",
      status: "Pending",
    },
  ],
  quotes: [
    {
      id: 301,
      fixRequestId: 101,
      fixerId: "fixer-001",
      clientId: "client-001",
      description: "Fix kitchen sink, includes parts and labor.",
      amount: 15000,
      createdAt: "2024-07-23T08:00:00Z",
      items: [
        {
          id: 1,
          quoteId: 301,
          name: "Sink Pipe",
          quantity: 1,
          unitPrice: 5000,
          price: 5000,
        },
        {
          id: 2,
          quoteId: 301,
          name: "Labor",
          quantity: 1,
          unitPrice: 10000,
          price: 10000,
        },
      ],
      supportingImage: {
        id: 12,
        fileName: "quote-sink.jpg",
        fileType: "image/jpeg",
        fileUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
      },
      supportingDocument: {
        id: 13,
        fileName: "quote-sink.pdf",
        fileType: "application/pdf",
        fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      },
      supportingFiles: [],
    },
    {
      id: 302,
      fixRequestId: 102,
      fixerId: "fixer-002",
      clientId: "client-002",
      description: "Electrical wiring check and repair.",
      amount: 20000,
      createdAt: "2024-07-18T10:00:00Z",
      items: [
        {
          id: 3,
          quoteId: 302,
          name: "Wiring Materials",
          quantity: 1,
          unitPrice: 8000,
          price: 8000,
        },
        {
          id: 4,
          quoteId: 302,
          name: "Labor",
          quantity: 1,
          unitPrice: 12000,
          price: 12000,
        },
      ],
      supportingImage: {
        id: 14,
        fileName: "quote-wiring.jpg",
        fileType: "image/jpeg",
        fileUrl: "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80",
      },
      supportingDocument: {
        id: 15,
        fileName: "quote-wiring.pdf",
        fileType: "application/pdf",
        fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      },
      supportingFiles: [],
    },
    {
      id: 303,
      fixRequestId: 103,
      fixerId: "fixer-001",
      clientId: "client-003",
      description: "Install new water heater.",
      amount: 25000,
      createdAt: "2024-07-28T09:00:00Z",
      items: [
        {
          id: 5,
          quoteId: 303,
          name: "Water Heater",
          quantity: 1,
          unitPrice: 20000,
          price: 20000,
        },
        {
          id: 6,
          quoteId: 303,
          name: "Installation",
          quantity: 1,
          unitPrice: 5000,
          price: 5000,
        },
      ],
      supportingImage: {
        id: 16,
        fileName: "quote-heater.jpg",
        fileType: "image/jpeg",
        fileUrl: "https://images.unsplash.com/photo-1517816743773-6e0fd518b4a6?auto=format&fit=crop&w=400&q=80",
      },
      supportingDocument: {
        id: 17,
        fileName: "quote-heater.pdf",
        fileType: "application/pdf",
        fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      },
      supportingFiles: [],
    },
  ],
  payments: [
    {
      id: 401,
      clientId: "client-001",
      fixerId: "fixer-001",
      bookingId: 201,
      amount: 15000,
      clientPaymentStatus: "Paid",
      fixerPaymentStatus: "Received",
      createdAt: "2024-07-25T12:00:00Z",
    },
    {
      id: 402,
      clientId: "client-002",
      fixerId: "fixer-002",
      bookingId: 202,
      amount: 20000,
      clientPaymentStatus: "Paid",
      fixerPaymentStatus: "Received",
      createdAt: "2024-07-20T12:00:00Z",
    },
    {
      id: 403,
      clientId: "client-003",
      fixerId: "fixer-001",
      bookingId: 203,
      amount: 25000,
      clientPaymentStatus: "Pending",
      fixerPaymentStatus: "Pending",
      createdAt: "2024-07-30T12:00:00Z",
    },
  ],
  invoices: [
    {
      id: 501,
      clientId: "client-001",
      fixerId: "fixer-001",
      bookingId: 201,
      amount: 15000,
      createdAt: "2024-07-25T12:00:00Z",
      invoiceNumber: "INV-20240725-001",
    },
    {
      id: 502,
      clientId: "client-002",
      fixerId: "fixer-002",
      bookingId: 202,
      amount: 20000,
      createdAt: "2024-07-20T12:00:00Z",
      invoiceNumber: "INV-20240720-002",
    },
    {
      id: 503,
      clientId: "client-003",
      fixerId: "fixer-001",
      bookingId: 203,
      amount: 25000,
      createdAt: "2024-07-30T12:00:00Z",
      invoiceNumber: "INV-20240730-003",
    },
  ],
  notifications: [
    {
      id: 601,
      userId: "client-001",
      title: "Booking Confirmed",
      message: "Your booking for 'Fix leaking kitchen sink' is confirmed.",
      type: "Booking",
      isRead: false,
      createdAt: "2024-07-24T09:00:00Z",
      relatedEntityId: "201",
    },
    {
      id: 602,
      userId: "client-002",
      title: "Payment Successful",
      message: "Your payment of ₦20,000 was successful.",
      type: "Payment",
      isRead: true,
      createdAt: "2024-07-20T12:05:00Z",
      relatedEntityId: "402",
    },
    {
      id: 603,
      userId: "client-003",
      title: "Quote Received",
      message: "You have received a new quote for your water heater installation.",
      type: "Quote",
      isRead: false,
      createdAt: "2024-07-28T10:00:00Z",
      relatedEntityId: "303",
    },
  ],
  fixerRatings: [
    {
      id: 701,
      clientId: "client-001",
      fixerId: "fixer-001",
      rating: 5,
      review: "Excellent work, very professional.",
      createdAt: "2024-07-26T10:00:00Z",
    },
    {
      id: 702,
      clientId: "client-002",
      fixerId: "fixer-002",
      rating: 4,
      review: "Good job, but arrived late.",
      createdAt: "2024-07-21T11:00:00Z",
    },
    {
      id: 703,
      clientId: "client-003",
      fixerId: "fixer-001",
      rating: 5,
      review: "Fast and clean installation.",
      createdAt: "2024-07-31T11:00:00Z",
    },
  ],
  chatMessages: [
    {
      id: 801,
      senderId: "client-001",
      receiverId: "fixer-001",
      message: "Hi, when will you arrive?",
      sentAt: "2024-07-25T09:00:00Z",
      isRead: true,
      relatedFixRequestId: 101,
    },
    {
      id: 802,
      senderId: "fixer-001",
      receiverId: "client-001",
      message: "I'll be there by 10am.",
      sentAt: "2024-07-25T09:05:00Z",
      isRead: false,
      relatedFixRequestId: 101,
    },
    {
      id: 803,
      senderId: "client-002",
      receiverId: "fixer-002",
      message: "Can you come tomorrow?",
      sentAt: "2024-07-19T18:00:00Z",
      isRead: true,
      relatedFixRequestId: 102,
    },
    {
      id: 804,
      senderId: "fixer-002",
      receiverId: "client-002",
      message: "Yes, I'll be there.",
      sentAt: "2024-07-19T18:10:00Z",
      isRead: true,
      relatedFixRequestId: 102,
    },
    {
      id: 805,
      senderId: "client-003",
      receiverId: "fixer-001",
      message: "When can you install the heater?",
      sentAt: "2024-07-29T08:00:00Z",
      isRead: false,
      relatedFixRequestId: 103,
    },
  ],
};